### 1. Registrar Usuario Admin (Caso de Éxito)
POST http://localhost:3000/api/auth/register
Content-Type: application/json

{
  "email": "admin@mitienda.com",
  "password": "passwordSegura123",
  "name": "Admin Principal"
}

###

### 2. Prueba de Error (Contraseña corta para probar Zod)
POST http://localhost:3000/api/auth/login
Content-Type: application/json

{
  "email": "admin@mitienda.com",
  "password": "passwordSegura12"
}